### ISSUE TITLE
Neovim Self-Closing

### ISSUE THREAD

**Issue by SergioRibera** [nickspoons/vim-sharpenup#6]
Neovim works correctly without this plugin, but as soon as I integrate it and it's loading some project (.proj) it just closes until the terminal.

**Nvim Version:** NVIM v0.5.0-dev+1075-g02a3c4179
**Terminal:** st (my own version)
**Mono Version:** 6.12.0

I attach an image of the plugins that I have installed in case that influences, besides the configuration that I tried to do.
![Vim-Screenshot_02052021_023758](https://user-images.githubusercontent.com/56278796/112592526-7f1f2080-8ddc-11eb-96e1-1fce5b17f013.png)
![Vim-Screenshot_02052021_023825](https://user-images.githubusercontent.com/56278796/112592529-80504d80-8ddc-11eb-88af-d7c9e06ce482.png)

If you need more details, I would be happy to provide them.

**Comment by nickspoons** [comment]
Can you please paste the actual text of your init.vim? I'm not going to type it out to try to repro... Ideally, post your full init.vim so I can try it myself.

What OS is this?

Just guessing here but here are some things to try:

1. In your plugin listings, move vim-sharpenup to _below_ OmniSharp-vim. vim-sharpenup is dependent on OmniSharp-vim so should be listed afterwards
2. Try disabling all other plugins to see if it's an interaction with another plugin causing the issue

**Comment by SergioRibera** [comment]
I have my init.vim somewhat dismembered and maybe with a lot of things wrong, so please don't judge xD.
I forgot to put my operating system, I'm sorry.

**SO**: ArchLinux
**init.vim**: https://termbin.com/eqm9
**plugins.vim**: https://termbin.com/hyjg
**pluginconfigs.vim**: https://termbin.com/22q34
**shortcuts.vim**: https://termbin.com/494q
**themes.vim**: https://termbin.com/cpwv

- I tried placing the plugin in the order you mention and the problem persists.
- I deactivated all, all plugins except OmniSharp-Vim and vim-sharpenup, the problem persists.

I did not manage to generate a log file for vim execution but if I did it would be very helpful.

**Comment by nickspoons** [comment]
OK it's a bit hard to debug a split up config like this. Could you try commenting out these lines and see if that changes things?

```vim
source ~/.config/nvim/pluginconfigs.vim
source ~/.config/nvim/shortcuts.vim
source ~/.config/nvim/themes.vim
```

And if it does, narrow it down to which script is the culprit?

**Comment by nickspoons** [comment]
I copied your config and tried running in archlinux with just OmniSharp-vim and vim-sharpenup. There are lots of errors due to other plugins and some strange config but after commenting some stuff out it works, nothing is hanging.

You say nvim just crashes and closes when you open a .proj file? This plugin shouldn't do anything in a .proj file...

**Comment by nickspoons** [comment]
Oh I think I see the problem. You are installing plugins into your `autoload` directory. I bet that's the culprit. This line:

```vim
call plug#begin('~/.config/nvim/autoload/plugged')
```

should be:

```vim
call plug#begin('~/.config/nvim/plugged')
```

(Before making this change, exit all nvims and just move the dir, to save vim-plug re-installing all your plugins:

```sh
mv ~/.config/nvim/autoload/plugged ~/.config/nvim/plugged
```

**Comment by nickspoons** [comment]
The previous comment is correct and you should definitely move that `plugged` dir out of  `autoload` ... but it still works for me like that. I have copied your entire config and there are no errors. But there are some worrying things there that I think could be causing problems. Like these autocmds, which are not in `augroup`s,:

```vim
au BufRead,BufNewFile *.ino,*.pde set filetype=cpp
" == AUTOCMD END ================================
autocmd FileType * command! -nargs=0 Prettier :CocCommand prettier.formatFile
```

And the `mkview`/`loadview`  autocmds.

Can you tell me exactly how you're producing the issue? Can you share the project?

**Comment by nickspoons** [comment]
Demo running your full config:

[![asciicast](https://asciinema.org/a/YGFqsiA25COb1FrOJnA5pjRKh.svg)](https://asciinema.org/a/YGFqsiA25COb1FrOJnA5pjRKh)

**Comment by SergioRibera** [comment]
I just tried everything you suggested, I moved my plugged folder to the place you mention, then I tried to open other c# projects and the truth is that the problem persists :c

**Comment by nickspoons** [comment]
OK. Let's try narrowing down what it is in vim-sharpenup which is causing conflicts, by disabling the individual parts of _this_ plugin.

```vim
" Disable codeaction lookup
let g:sharpenup_codeactions = 0
" Disable mappings
let g:sharpenup_create_mappings = 0
```

You haven't added lightline integration so don't need to do anything there.

So if you add those 2 lines above, does the error go away? What about with just one or the other?

**Comment by SergioRibera** [comment]
> OK. Let's try narrowing down what it is in vim-sharpenup which is causing conflicts, by disabling the individual parts of _this_ plugin.
> 
> ```viml
> " Disable codeaction lookup
> let g:sharpenup_codeactions = 0
> " Disable mappings
> let g:sharpenup_create_mappings = 0
> ```
> 
> You haven't added lightline integration so don't need to do anything there.
> 
> So if you add those 2 lines above, does the error go away? What about with just one or the other?

Apparently putting this in fixed it and now I can load any project without problems, but my question would be does this take away from my functionality? Because if there are certain things of this plugin that I would not like to lose, for example that popup that you open when you run `\os`

**Comment by nickspoons** [comment]
Yes these lines disable all of the plugin functionality 😄 

Can you try with just one of those lines, then the other, and work out which one is causing the error?

The popups I was opening are just OmniSharp-vim popups, but using the mappings which vim-sharpenup creates automatically. I was using `\osd` for the documentation popup (`:OmniSharpDocumentation`) and `<-\>` for the signature help (`:OmniSharpSignatureHelp`). You already have your own mappings for omnisharp so you possibly don't need the vim-sharpenup ones, just map the OmniSharp-vim functions you want.

**Comment by SergioRibera** [comment]
Thank you very much for all your help and patience, it has worked and I will be looking in depth to see what is causing this problem.

**Comment by SergioRibera** [comment]
Just to let you know, the problem appears at the moment of activating this, see if it helps you.

```vim
let g:sharpenup_codeactions = 0
```

**Comment by nickspoons** [comment]
Sorry, I am a bit unsure which line is making the error go away. Each of those 2 lines _disables_ part of the vim-sharpenup functionality.

So if you disable the mapping creation, your config is working correctly? You get the lightbulb icon (💡) popping up in lines where there are code actions available?

**Comment by nickspoons** [comment]
One last thing to test, if you don't mind (since I can't repro locally): if you add `finish` in your init.vim after sourcing all your scripts, at line 6, do you still get errors? You've already tested disabling all the other parts of your config, but not the other contents of your init.vim, so it would be good to know if something in the rest of the init.vim is conflicting somehow.

**Comment by SergioRibera** [comment]
Oh yes, I'm very interested in helping you, I'll let you know:

- The problem appears at the moment of having the actions activated.
- I don't see the lightbulb icon (💡)

now I will try to deactivate all my configuration except my init and my plugins and see what happens with all the default settings.

**Comment by SergioRibera** [comment]
Apparently it works without loading the other settings, but I still don't see the lightbulb icon.

**Comment by SergioRibera** [comment]
I come to update the situation, something in my `pluginconfigs.vim` file is not liking to coexist with `sharpenup` and I have strong suspicions that `Coc-vim` is the culprit..

**Comment by SergioRibera** [comment]
I found the problem from the root and I'm sorry for the inconvenience, the problem is that I use a terminal (custom fork of st-suckless) and my version does not support fonts that have not been explicitly indicated to be used and the bulb icon is a non-unicode icon so I had problems with it, solution:

- Change the default bulb icon to a Unicode one from Nerd Fonts.
```vim
let g:sharpenup_codeactions_glyph = ''
```

**Comment by nickspoons** [comment]
Ok great, glad to get to the root of the problem!
